In [4]:
import numpy as np
import numpy.linalg as la

In [6]:
def eigen(A):
    w,v=la.eig(a)
    print('Eigen-values:', w)
    print('E-vectors', v)

In [15]:
A=np.array(([2,1,0,-1],[0,-1,1,1]))
print(la.svd(A))
print(A.T@A)
print(la.eig(A.T@A))

(array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]), array([2.64575131, 1.41421356]), array([[-0.6761234 , -0.50709255,  0.16903085,  0.50709255],
       [ 0.63245553, -0.31622777,  0.63245553,  0.31622777],
       [-0.36035675,  0.57366534,  0.72071349, -0.14704815],
       [ 0.11401824,  0.5601475 , -0.22803648,  0.78818398]]))
[[ 4  2  0 -2]
 [ 2  2 -1 -2]
 [ 0 -1  1  1]
 [-2 -2  1  2]]
(array([ 7.00000000e+00,  2.00000000e+00,  0.00000000e+00, -4.15071381e-16]), array([[-6.76123404e-01,  6.32455532e-01, -9.89601402e-18,
        -3.52760088e-01],
       [-5.07092553e-01, -3.16227766e-01,  7.07106781e-01,
         6.06652036e-01],
       [ 1.69030851e-01,  6.32455532e-01,  1.97920280e-17,
         7.05520176e-01],
       [ 5.07092553e-01,  3.16227766e-01,  7.07106781e-01,
        -9.88681398e-02]]))
