In [25]:
import numpy as np
import numpy.linalg as la
from numpy import matmul as mult

In [15]:
A=np.vstack(([1,2,1],[0,1,-1],[1,3,0]))
b=np.asarray([4,1,0])

In [73]:
print(A)
U,S,V=la.svd(A,full_matrices=False)

S=np.diag(S)
S=np.delete(S, 2, 1)
S=np.delete(S, 2, 0)
V=V.T
Vr = np.delete(V, 2, 1)
Ur=np.delete(U,2,1)
DI=la.inv(D)
xhat=Vr@DI@Ur.T@b
print(xhat)

[[ 1  2  1]
 [ 0  1 -1]
 [ 1  3  0]]
[0.48484848 0.39393939 1.06060606]


In [74]:
print(mult(A,xhat))

[ 2.33333333 -0.66666667  1.66666667]
